### ISSUE TITLE
Problem when target sd card has more or less partitions

### ISSUE THREAD

**Issue by danielandross** [qrti/shrink#2]
First of all thank you for this great script!
My run ended abnormally because my target sd had only one partition so it failed to unmount the second. I think you cannot assume that any sd card to overwrite had two partitions as well.

**Comment by armtir** [comment]
change line 58, 58 to 

PART1="${DEVICE}p1"
PART2="${DEVICE}p2"

**Comment by qrti** [comment]
V0.7 might help, couldn't try it out with real single partition raspi images, so if you like, try it out and report ...

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
I thought this was an issue, too, but it turns out I wasn't paying attention (big surprise there!). As the instructions say, a device might show up as several partitions (/dev/sdb1 and /dev/sdb2 in my case). Simply update the script to say DEVICE="/dev/sdb". That is, omit the numbers.
