### ISSUE TITLE
Problem when using SD Card adaptors

### ISSUE THREAD

**Issue by danielandross** [qrti/shrink#3]
First of all thank you for this handy script!
I encountered a problem as the script only handles adaptors whose devices are named /dev/sdx but it fails right at the start for common adaptors named /dev/mmcblk0p

**Comment by armtir** [comment]
Change:
Line 12:
`DEVICE="/dev/mmcblk0"                   # source and target SD card device       `


Line 57, 58:
```
PART1="${DEVICE}p1"
PART2="${DEVICE}p2"
```

**Comment by qrti** [comment]
V0.7 should work for mmcblk devices now
