### ISSUE TITLE
computing start offset with parted fail

### ISSUE THREAD

**Issue by avilleret** [qrti/shrink#4]
with parted 3.2 the line https://github.com/qrti/shrink/blob/master/script/shrink.sh#L81 set start offset to 0
then image is mount without offset and all partitions are displayed and we can't resize it with gparted

the culprit is `parted`, I think the line should looks like : 

    start="$(sudo parted $IMAGE -ms unit s print | grep "^2" | cut -f2 -d: | sed 's/[^0-9]*//g')"

with `print` instead of `p`

**Comment by qrti** [comment]
my parted 3.2 version works with p and print correct, changed p to print anyway
