### ISSUE TITLE
Add a hint on where to save the Gparted details

### ISSUE THREAD

**Issue by brennerm** [qrti/shrink#8]
`press button 'Save Details' and 'Save' in file requester` doesn't really tell me where to save it. After reading through the code the default search path is `~/gparted_details.htm`.

Maybe this path should be added to the instruction printed on the command line.

**Comment by bitdruid** [comment]
drove me crazy: placed file wrong 3 times and as a result a 128 GB SD card started to backup from scratch. i ended up modifying the script to jump over and use existing img with gparted_details...

**Comment by qrti** [comment]
done, thank you for the hint!
